language: node_js

dist: xenial

services:
  - xvfb

os:
  - osx
  - linux

node_js:
  - "node"

install:
  - npm install

script:
  - npm test --silent

after_success:
  - bash <(curl -s https://codecov.io/bash)
