name: Mark stale issues and PRs

on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - name: Mark stale issues and PRs
        uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue has had no activity for a while"
          stale-pr-message: "This pull request has had no activity for a while"
          stale-issue-label: "stale"
          stale-pr-label: "stale"
